# Generated by Django 5.1.2 on 2024-11-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_documentstorage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
