# Generated by Django 5.1.2 on 2024-10-29 17:09

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BikeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=100)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('brand', models.CharField(max_length=100)),
                ('color_edition', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('bike_class', models.CharField(max_length=50)),
                ('daily_deposit', models.IntegerField(blank=True, null=True)),
                ('monthly_deposit', models.IntegerField(blank=True, null=True)),
                ('daily_rental', models.IntegerField(blank=True, null=True)),
                ('weekly_rental', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField()),
                ('rental_days', models.IntegerField()),
                ('rental_price', models.IntegerField(blank=True, null=True)),
                ('price_deposit', models.IntegerField(blank=True, null=True)),
                ('price_deposit_addon', models.IntegerField(blank=True, null=True)),
                ('addons', models.ManyToManyField(blank=True, null=True, related_name='rental_addons', to='inventory.addon')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_member', to='account.member')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_vehicle', to='inventory.bikeinventory')),
            ],
        ),
    ]
