# Generated by Django 5.1.2 on 2024-10-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
