# Generated by Django 5.1.2 on 2024-11-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_addon_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeinventory',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
