# Generated by Django 5.1.2 on 2024-11-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_bikeinventory_bike_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentallog',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='rental_addons', to='inventory.addon'),
        ),
    ]
